version: "3"

services:
  nuxt:
    build: .
    restart: always
    expose: 
      - 3000
    command:
      "npm run start"

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
